### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'hidden'

### ISSUE THREAD

**Issue by pengbo-learn** [KentoW/melody-conditioned-lyrics-language-model#1]
`------ Parameters -----
            midi:  ./sample_data/sample.midi
          output:  ./output
           param:  ./checkpoint/model.param.json
      checkpoint:  ./checkpoint/model_05.pt
            seed:  0
          window:  20
     temperature:  1.0
Traceback (most recent call last):
  File "generate.py", line 442, in <module>
    main(args)
  File "generate.py", line 421, in main
    temperature=args.temperature)
  File "generate.py", line 159, in generate
    syllable_output, lyrics_output, hidden = model(x_word, x_midi, lengths+1)
  File "/dockerdata/boarpeng/nlp_engine/env_lyric/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'hidden'
`
Throwing this error when I run 
`python generate.py -midi ./sample_data/sample.midi -param ./checkpoint/model.param.json -checkpoint ./checkpoint/model_05.pt -output ./output`
I try to fix this error by adding missing param hidden, this will instead throw another error
`RuntimeError: Expected hidden[0] size (1, 20, 768), got (1, 1, 768)`

**Comment by KentoW** [comment]
Thanks for your comment.
I revised `generate.py`.
